### ISSUE TITLE
Pokedex crash bug

### ISSUE THREAD

**Issue by schkrisz1** [Pokecube-Development/Pokecube-Issues-and-Wiki#1084]
## Read and then Delete this section - If this is in your bug report, it will be closed.
Any issues which report bugs, must fill out this form, otherwise they will be immediately closed with no response.
If your bug involves a crash, it *MUST* include a crash report. Failure to include the crash report without a good reason to not include it, will result in your issue being immediately closed.

#### Issue Description:
Pokedex crash

#### What happens:

Dear developer!
The mod is very good, BUT when I use the pokedex, exactly when I want to scroll through the dex, the game crashes and closes itself.
Please fix this bug in future updates.
Thanks

#### What you expected to happen:

I was hoping that it wouldn't close the game when I'm scrolling through pokedex in the pokedex.

#### Steps to reproduce:

1. I can browse the pokedex without crashing.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: v.3.19.4
- Minecraft: v1.19.2
- Forge: v43.1.47

**Comment by Thutmose** [comment]
Please include the crash report, and logs

**Comment by Thutmose** [comment]
the crash report should be in the crash-reports folder
logs are in the logs folder

**Comment by Thutmose** [comment]
this should be fixed for next update, if you include a crash report next time I will get it fixed faster...

**Comment by schkrisz1** [comment]
---- Minecraft Crash Report ----


Time: 2022-11-06 09:23:37
Description: keyPressed event handler

java.lang.NullPointerException: Cannot invoke "pokecube.api.entity.pokemob.IPokemob.getCustomHolder()" because "this.pokemob" is null
	at pokecube.core.client.gui.GuiPokedex.initList(GuiPokedex.java:179) ~[pokecube-aio-1.19.2-3.19.4.jar%23156!/:3.19.4] {re:classloading}
	at pokecube.core.client.gui.GuiPokedex.handleButton(GuiPokedex.java:122) ~[pokecube-aio-1.19.2-3.19.4.jar%23156!/:3.19.4] {re:classloading}
	at pokecube.core.client.gui.GuiPokedex.m_7933_(GuiPokedex.java:262) ~[pokecube-aio-1.19.2-3.19.4.jar%23156!/:3.19.4] {re:classloading}
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$4(KeyboardHandler.java:353) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:343) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:441) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.47.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pokecube.core.client.gui.GuiPokedex.initList(GuiPokedex.java:179) ~[pokecube-aio-1.19.2-3.19.4.jar%23156!/:3.19.4] {re:classloading}
	at pokecube.core.client.gui.GuiPokedex.handleButton(GuiPokedex.java:122) ~[pokecube-aio-1.19.2-3.19.4.jar%23156!/:3.19.4] {re:classloading}
	at pokecube.core.client.gui.GuiPokedex.m_7933_(GuiPokedex.java:262) ~[pokecube-aio-1.19.2-3.19.4.jar%23156!/:3.19.4] {re:classloading}
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$4(KeyboardHandler.java:353) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:343) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:441) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
-- Affected screen --
Details:
	Screen name: pokecube.core.client.gui.GuiPokedex
Stacktrace:
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:343) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:441) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23130!/:build 7] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23138!/:build 7] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.47.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['schkriszking19'/1468, l='ClientLevel', x=466.31, y=68.00, z=-270.05]]
	Chunk stats: 289, 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (478,65,-288), Section: (at 14,1,0 in 29,4,-18; chunk contains blocks 464,-64,-288 to 479,319,-273), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 379000 game time, 274188 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:717) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:securitycraft.mixins.json:camera.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.47.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1303509456 bytes (1243 MiB) / 3154116608 bytes (3008 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD FX-8370 Eight-Core Processor               
	Identifier: AuthenticAMD Family 21 Model 2 Stepping 0
	Microarchitecture: Piledriver
	Frequency (GHz): 4.02
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=26.20.12028.2
	Graphics card #1 name: AMD Radeon R7 200 Series
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x683f
	Graphics card #1 versionInfo: DriverVersion=26.20.12028.2
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 0.80
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 0.80
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 0.67
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 0.67
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 24022.50
	Virtual memory used (MB): 18755.34
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 37.01
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.2-forge-43.1.47
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Radeon RX 570 Series GL version 3.2.13559 Core Profile Forward-Compatible Context 26.20.12028.2, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD FX-8370 Eight-Core Processor 
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.1.47.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.47.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.1.47.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.1.47.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.47.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		youritemsaresafe_1.19.2-2.0.jar                   |Your Items Are Safe           |youritemsaresafe              |2.0                 |DONE      |Manifest: NOSIGNATURE
		pokecube-aio-1.19.2-3.19.4.jar                    |Pokécube Core                 |pokecube                      |3.19.4              |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.19.2-9.0.0-153.jar         |Immersive Engineering         |immersiveengineering          |1.19.2-9.0.0-153    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		architectury-6.3.49-forge.jar                     |Architectury                  |architectury                  |6.3.49              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1902.3.9-build.144.jar          |FTB Library                   |ftblibrary                    |1902.3.9-build.144  |DONE      |Manifest: NOSIGNATURE
		engineersdecor-1.19.2-forge-1.3.26.jar            |Engineer's Decor              |engineersdecor                |1.3.26              |DONE      |Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		furnish-16-1.19.jar                               |Furnish                       |furnish                       |16-1.19             |DONE      |Manifest: NOSIGNATURE
		prefab-1.9.2.3.jar                                |Prefab                        |prefab                        |1.9.2.3             |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1902.2.9-build.61.jar             |FTB Teams                     |ftbteams                      |1902.2.9-build.61   |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1902.3.9-build.168.jar           |FTB Chunks                    |ftbchunks                     |1902.3.9-build.168  |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.1.47-universal.jar                |Forge                         |forge                         |43.1.47             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		furnitureexpanded-1.19.2-1.0.1.jar                |Furniture Expanded            |furnitureexpanded             |1.19-1.0.1          |DONE      |Manifest: NOSIGNATURE
		collective-1.19.2-5.13.jar                        |Collective                    |collective                    |5.13                |DONE      |Manifest: NOSIGNATURE
		Decoration+Mod+1.10+(Ver+1.19.2).jar              |Decoration and Furniture      |decoration_mod                |1.10                |DONE      |Manifest: NOSIGNATURE
		[1.19.2]+SecurityCraft+v1.9.3.1.jar               |SecurityCraft                 |securitycraft                 |1.9.3.1             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 3890b911-28a5-4edb-94bb-5b116fadb9a2
	FML: 43.1
	Forge: net.minecraftforge:43.1.47

**Comment by Thutmose** [comment]
3.19.5 should have the fix for this in it

**Comment by schkrisz1** [comment]
ok thanks.

**Comment by Thutmose** [comment]
should be fixed here when available: https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi/files/4073453
