### ISSUE TITLE
Pokerestore not working

### ISSUE THREAD

**Issue by Kaitocain** [Pokecube-Development/Pokecube-Issues-and-Wiki#112]
#### Issue Description:
Pokerestore fails to work

#### What happens:
Pokerestore fails to work

#### What you expected to happen:
Pokerestore should give me a list of pokemon to restore

#### Steps to reproduce:

1. Use /pokerestore @p check

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube AIO: 1.15.12
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

Can be tested by loading the Pokecube Adventures Evolved Quest Edition Modpack and attempting to use Pokerestore after catching a pokemon

Error From Log Included Below:
```
[16:09:09] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: pokerestore @p check
java.lang.NullPointerException: null
	at thut.core.common.handlers.PlayerDataHandler.getPlayerData(PlayerDataHandler.java:141) ~[PlayerDataHandler.class:?]
	at pokecube.core.commands.RestoreCommand.execute(RestoreCommand.java:77) ~[RestoreCommand.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
	at net.minecraft.util.Util.runTask(Util.java:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

```

Including Full Modlist (if needed): (All mods up to date)
The Aether
Ai Improvements
AppleSkin
Aquaculture
Bailey's Dailies
Better Advancements 
BiblioCraft 
Bountiful 
Carry On 
Comforts
Cooking for Blockheads
Cosmetic Armor Reworked
Dungeon Tactics
Doomlike Dungeons
Extra Alchemy
Fast Leaf Decay
Future MC
Gravestone Mod
Inventory Tweaks
JEI
NetherEX
Pams HarvestCraft 
PokeCube AIO
Progressive Bosses
Roguelike Dungeons
Simple Harvest
VanillaFix
Waystones
BetterFPS
FoamFix for Minecraft
Phosphor 
Pyramid Plunder 
Vanillatweaks
Aether Continuation
Aether: Lost Content
Mouse tweaks
Rustic 
Dawn of time: builders Edition
ConnectedtexturesMod
Chisel
FastWorkbench
FastFurnace
Mowzie's Mobs
Living Enchantment
Electroblob's Wizardry
Magic Seeds for Electroblobs Wizardry 
DiscordSuite
BnBGamingCore
BNBGamingLib 
Bookshelf 
Chameleon
CompatSkills
CraftTweaker
Customized Dungeon Loot
Dimension Stages
Dimension Keys
Game Stages
Guidebook
Item Blacklist
Item Stages
IvToolkit 
Lapis Stays in the Enchating Table
LibraryEx
LLibrary
LootTweaker
Lost Cities 
Lost Souls 
Minecraft Comes Alive
Patchouli
Project: Vibrant Journeys
PTRLib
RandomTweaks
Reskillable
Scaling Health
Scaling Wealth 
Shadowfacts' Forgelin
Shield Parry
Silent Lib
Traverse Legacy 
Triumph
Tropicraft
VeinMiner
Atum 2

**Comment by Thutmose** [comment]
you have your arguments backwards, the last one should be the player
