### ISSUE TITLE
1.14.4 crash on dedicated server

### ISSUE THREAD

**Issue by SSE4** [Pokecube-Development/Pokecube-Issues-and-Wiki#154]
#### Issue Description:

running forge dedicated server with pokecube aio 2.0.0.0e results in errors, so it's impossible to use this mod at all

#### What happens:

several fatal errors and crashes:
```
[25Jan2020 13:49:23.406] [modloading-worker-1/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class thut/core/client/render/tabula/model/modelbase/TabulaModelBase for invalid dist DEDICATED_SERVER
[25Jan2020 13:49:23.410] [modloading-worker-1/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.RuntimeException: Attempted to load class thut/core/client/render/tabula/model/modelbase/TabulaModelBase for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.14.4-28.1.116.jar:28.1]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102) ~[modlauncher-4.1.0.jar:4.1.0+62+5bfa59b]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-1.0.0-service.jar:?]
        at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-1.0.0-service.jar:?]
        at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:20) ~[eventbus-1.0.0-service.jar:?]
        at net.minecraftforge.eventbus.service.ModLauncherService.processClass(ModLauncherService.java:19) ~[eventbus-1.0.0-service.jar:1.0.0+54+3f83a9e]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102) ~[modlauncher-4.1.0.jar:4.1.0+62+5bfa59b]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        at thut.core.client.render.model.ModelFactory.<clinit>(ModelFactory.java:29) ~[?:2.0.0.e]
        at pokecube.mobs.PokecubeMobs.<init>(PokecubeMobs.java:153) ~[?:2.0.0.e]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_241]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_241]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:28.1]
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_241]
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_241]
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
        at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_241]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[?:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_241]
        at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:134) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) [?:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_241]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_241]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_241]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_241]

```
```
[25Jan2020 13:49:23.429] [modloading-worker-1/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class thut/core/client/render/tabula/components/ModelJson for invalid dist DEDICATED_SERVER
[25Jan2020 13:49:23.434] [modloading-worker-1/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: pokecube_mobs, class pokecube.mobs.PokecubeMobs
java.lang.ExceptionInInitializerError: null
        at pokecube.mobs.PokecubeMobs.<init>(PokecubeMobs.java:153) ~[?:2.0.0.e]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_241]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_241]
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:28.1]
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_241]
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_241]
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
        at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_241]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_241]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[?:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_241]
        at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:134) ~[?:?]
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) [?:1.8.0_241]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_241]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_241]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_241]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_241]
Caused by: java.lang.RuntimeException: Attempted to load class thut/core/client/render/tabula/components/ModelJson for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.14.4-28.1.116.jar:28.1]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:102) ~[modlauncher-4.1.0.jar:4.1.0+62+5bfa59b]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:80) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128) ~[modlauncher-4.1.0.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-4.1.0.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
        at thut.core.client.render.model.ModelFactory.<clinit>(ModelFactory.java:29) ~[?:2.0.0.e]
        ... 30 more

```

as result, server doesn't start (terminates):
```
[25Jan2020 13:58:23.782] [Server thread/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[25Jan2020 13:58:23.783] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Pokecube Mobs (pokecube_mobs) has failed to load correctly
§7null
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?]
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?]
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[25Jan2020 13:58:23.856] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: /opt/minecraft/forge/./crash-reports/crash-2020-01-25_13.58.23-server.txt
[25Jan2020 13:58:23.899] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[25Jan2020 13:58:23.903] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[25Jan2020 13:58:23.906] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:182) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:979) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:521) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:553) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:544) ~[?:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:661) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]

```

#### What you expected to happen:

at least, allow to launch server gracefully.

#### Steps to reproduce:

1. install forge server
2. place **pokecube-aio-1.14.4-2.0.0.e.jar** into the mods subdirectory
3. start the server
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube Core: 2.0.0.0e
- Pokecube Revival (if applicable): 2.0.0.0e
- Pokecube Mobs (if applicable): 2.0.0.0e
- Minecraft: 1.14.4
- Forge: 1.14.4-28.1.116

crash report:
```
---- Minecraft Crash Report ----
// Sorry :(

Time: 1/25/20 1:58 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Pokecube Mobs (pokecube_mobs) has failed to load correctly
§7null
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
        Minecraft Version: 1.14.4
        Minecraft Version ID: 1.14.4
        Operating System: Linux (amd64) version 4.19.0-5-cloud-amd64
        Java Version: 1.8.0_241, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 2693859600 bytes (2569 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
        CPUs: 1
        JVM Flags: 7 total; -Xmx3072M -Xms3072M -XX:+UseG1GC -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
        ModLauncher: 4.1.0+62+5bfa59b
        ModLauncher launch target: fmlserver
        ModLauncher naming: srg
        ModLauncher services:
                /eventbus-1.0.0-service.jar eventbus PLUGINSERVICE
                /forge-1.14.4-28.1.116.jar object_holder_definalize PLUGINSERVICE
                /forge-1.14.4-28.1.116.jar runtime_enum_extender PLUGINSERVICE
                /accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE
                /forge-1.14.4-28.1.116.jar capability_inject_definalize PLUGINSERVICE
                /forge-1.14.4-28.1.116.jar runtimedistcleaner PLUGINSERVICE
                /forge-1.14.4-28.1.116.jar fml TRANSFORMATIONSERVICE
        FML: 28.1
        Forge: net.minecraftforge:28.1.116
        FML Language Providers:
                javafml@28.1
                minecraft@1
        Mod List:
                forge-1.14.4-28.1.116-server.jar Minecraft {minecraft@1.14.4 CREATE_REGISTRIES}
                followingvillagers-1.14.4-1.2.0.jar Following Villagers {followingvillagers@1.14.4-1.2.0 CREATE_REGISTRIES}
                theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE CREATE_REGISTRIES}
                Floocraft+1.14.4-1.10.0.jar Floocraft {floocraftft@1.10.0 CREATE_REGISTRIES}
                AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
                Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version CREATE_REGISTRIES}
                AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 CREATE_REGISTRIES}
                jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 CREATE_REGISTRIES}
                JustEnoughResources-1.14.4-0.10.0.70.jar Just Enough Resources {jeresources@0.10.0.70 CREATE_REGISTRIES}
                ProjectE-1.14.4-PE1.0.1B.jar ProjectE {projecte@1.14.4-PE1.0.1B CREATE_REGISTRIES}
                forge-1.14.4-28.1.116-universal.jar Forge {forge@28.1.116 CREATE_REGISTRIES}
                pokecube-aio-1.14.4-2.0.0.e.jar Thut Core {thutcore@2.0.0.e CREATE_REGISTRIES, thutcrafts@2.0.0.e CREATE_REGISTRIES, thut_wearables@2.0.0.e CREATE_REGISTRIES, thut_bling@2.0.0.e CREATE_REGISTRIES, pokecube@2.0.0.e CREATE_REGISTRIES, pokecube_mobs@2.0.0.e ERROR, pokecube_adventures@2.0.0.e CREATE_REGISTRIES}
                CraftingTweaks_1.14.4-10.2.1.jar Crafting Tweaks {craftingtweaks@10.2.1 CREATE_REGISTRIES}
                StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 CREATE_REGISTRIES}
        Data Packs:
        Is Modded: Definitely; Server brand changed to 'forge'
        Type: Dedicated Server (map_server.txt)
```

**Comment by Thutmose** [comment]
fixed for next update, there are still a couple other things to work one, but once it is done, this issue should be gone in 2.0.0.f

**Comment by Thutmose** [comment]
2.0.0.f has been uploaded to curseforge, it should fix this, please close the issue after confirming

**Comment by SSE4** [comment]
do you have a link? I don't see *2.0.0.f* here: https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi/files

**Comment by Thutmose** [comment]
great... still "under review"... I will see about adding it to the "releases" for this github, I will update this issue with a link when I have one

**Comment by Thutmose** [comment]
https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/releases/tag/2.0.0.f

**Comment by SSE4** [comment]
@Thutmose yes, now it's working like a charm
