### ISSUE TITLE
General Pokemob Model/Texture issues

### ISSUE THREAD

**Issue by Thutmose** [Pokecube-Development/Pokecube-Issues-and-Wiki#319]
# Master list of Pokemob  Model related issues

Note that any issue which is related to a model or texture, will be closed, and the comment should be mentioned here instead.

## Known Missingnos:

-  [ ] impidimp line

## Models with bugged model/textures:

- [ ] placeholder

## Old models to re-make

- [ ] placeholder

**Comment by MetaltyrantMk2** [comment]
Sentret line has broken necks while sentrets vision isnt connected to its facial area but to the top of its head

**Comment by MetaltyrantMk2** [comment]
Skwovet line is missingno

**Comment by MetaltyrantMk2** [comment]
Vivillon is missing its region based wing colors

**Comment by Thutmose** [comment]
we need to see how many of the ones in #208 are still around

**Comment by MetaltyrantMk2** [comment]
West Sea Shellos has a broken model and is missing its color

**Comment by MetaltyrantMk2** [comment]
Alolan Ninetales is missing its texture

**Comment by deathxf** [comment]
Mega metagross have a bug on a model

**Comment by MetaltyrantMk2** [comment]
Reshiram is T-posing

**Comment by MetaltyrantMk2** [comment]
Shiny snivy has a hole in its head

**Comment by Thutmose** [comment]
#372 here as well

**Comment by Aunknownperson** [comment]
<img width="632" alt="volcarona" src="https://user-images.githubusercontent.com/64693020/82250757-10e71300-991a-11ea-87ad-135946da8d2d.png">

missing an entire wing

**Comment by Aunknownperson** [comment]
<img width="758" alt="yvetal" src="https://user-images.githubusercontent.com/64693020/82250772-18a6b780-991a-11ea-85c7-43bc69c74f5c.png">

the spikes(idk where they are supposed to be, but clearly not floating in 1 spot 24/7 XD)

**Comment by Aunknownperson** [comment]
<img width="585" alt="aerodactyl" src="https://user-images.githubusercontent.com/64693020/82250818-2c521e00-991a-11ea-9589-1da732e947a4.png">

on both sides of aerodactlye wings, there are holes behind the hands

**Comment by Aunknownperson** [comment]
<img width="494" alt="latias and latios" src="https://user-images.githubusercontent.com/64693020/82250876-468bfc00-991a-11ea-907d-47583a785547.png">

mega latas/latios have paper thin ears or what ever these things are, they should have 3D like effect like normal form latias/latios

**Comment by Aunknownperson** [comment]
<img width="589" alt="abra" src="https://user-images.githubusercontent.com/64693020/82251177-bb5f3600-991a-11ea-995e-2ac3200de6d3.png">

abras arms are all types of messed up

**Comment by Aunknownperson** [comment]
<img width="580" alt="staryu" src="https://user-images.githubusercontent.com/64693020/82251317-f6616980-991a-11ea-9614-1967952cb225.png">

staryu dosnt have a yellow patch area behind it in the show/games(im pretty sure, i could be wrong though)

**Comment by deathxf** [comment]
Xray effect on the bergmite 
![image](https://user-images.githubusercontent.com/52356643/82378737-13ba3480-99fc-11ea-827e-def71bf6f1b8.png)

**Comment by WenXin20** [comment]
Vivillon's wings are cut off at the top.

**Comment by WenXin20** [comment]
Unfezant is missing walking/flying animations

**Comment by WenXin20** [comment]
Thievuls look like they are moon walking.

**Comment by WenXin20** [comment]
Furrets' shadow is too big

**Comment by WenXin20** [comment]
Hamper also has no animations

**Comment by WenXin20** [comment]
Bouffalant is missing it's face texture.
<details>
  <summary>Log</summary>

  ```
[20:14:09] [Render thread/WARN]: Failed to load texture: pokecube_mobs:gen_5/entity/textures/bouffalanthead.png
java.io.FileNotFoundException: pokecube_mobs:gen_5/entity/textures/bouffalanthead.png
	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:60) ~[?:?]
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:59) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture$TextureData.func_217799_a(SimpleTexture.java:113) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_215246_b(SimpleTexture.java:85) ~[?:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_195413_a(SimpleTexture.java:38) ~[?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_230183_b_(TextureManager.java:118) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_229263_a_(TextureManager.java:96) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_229269_d_(TextureManager.java:79) [?:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:63) [?:?]
	at net.minecraft.client.renderer.RenderState$TextureState.lambda$new$0(RenderState.java:690) [?:?]
	at net.minecraft.client.renderer.RenderState$TextureState$$Lambda$5312/1325965169.run(Unknown Source) [?:?]
	at net.minecraft.client.renderer.RenderState.func_228547_a_(RenderState.java:197) [?:?]
	at net.minecraft.client.renderer.RenderType$Type$$Lambda$18596/1330867862.accept(Unknown Source) [?:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) [guava-21.0.jar:?]
	at net.minecraft.client.renderer.RenderType$Type.lambda$new$0(RenderType.java:837) [?:?]
	at net.minecraft.client.renderer.RenderType$Type$$Lambda$5525/2058925178.run(Unknown Source) [?:?]
	at net.minecraft.client.renderer.RenderState.func_228547_a_(RenderState.java:197) [?:?]
	at net.minecraft.client.renderer.RenderType.func_228631_a_(RenderType.java:463) [?:?]
	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.func_228462_a_(IRenderTypeBuffer.java:129) [?:?]
	at net.minecraft.client.renderer.IRenderTypeBuffer$Impl.func_228461_a_(IRenderTypeBuffer.java:115) [?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:1781) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1005) [?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:686) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.31.jar:31.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/560990653.call(Unknown Source) [forge-1.15.2-31.2.31.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
  ```
  
</details>
<details>
  <summary>Picture</summary>
  
![2020-08-04_21 10 09](https://user-images.githubusercontent.com/12000593/90084287-917b9c80-dcda-11ea-83eb-f9e738e48c86.png)
  
</details>

**Comment by WenXin20** [comment]
Only Hawlucha's head moves when it flies/glides.

**Comment by WenXin20** [comment]
The hitbox for Gigantamax Charizard is too small

**Comment by WenXin20** [comment]
Crabcrawler has no walking animation

**Comment by WenXin20** [comment]
Turtonator is missing a walking animation

**Comment by lunapanshiel** [comment]
i came across a single spinda whose spots were rapidly flickering and crawling across it's head like an infestation of lice, using the official pokecube modpack

**Comment by lunapanshiel** [comment]
mareanie's face texture when blinking is broken, causing the middle tooth to split apart

**Comment by DarianLStephens** [comment]
Squawkabilly is a missingno in Minecraft 1.20.1, Pokecube version 1-3.24.0.i
![2024-02-06_23 23 46](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/assets/15375876/5f3a37cd-6829-494a-8ef4-236587850dec)
