### ISSUE TITLE
Startup Error for 1.16.5

### ISSUE THREAD

**Issue by aqswde40** [Pokecube-Development/Pokecube-Issues-and-Wiki#782]
#### What happens:
-- MOD pokecube_legends ---- MOD pokecube_legends --Details: Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/EntityTeleportEvent at pokecube.legends.spawns.WormholeSpawns.init(WormholeSpawns.java:142) ~[?:3.12.1] {re:classloading,pl:capability_inject_definalize:A} at pokecube.legends.init.SetupHandler.setup(SetupHandler.java:15) ~[?:3.12.1] {re:classloading} at net.minecraftforge.eventbus.ASMEventHandler_196_SetupHandler_setup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {} at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.eventbus.EventBus$$Lambda$2609/428506348.invoke(Unknown Source) ~[?:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading} at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading} at net.minecraftforge.fml.ModContainer$$Lambda$3252/47710680.run(Unknown Source) ~[?:?] {} at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {} at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {} at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {} at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames} at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
Mod File: pokecube-aio-1.16.5-3.12.1.jar Failure message: Pokécube Legends (pokecube_legends) encountered an error during the common_setup event phase java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/EntityTeleportEvent Mod Version: 3.12.1 Mod Issue URL: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.EntityTeleportEventStacktrace: at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {} at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {} at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading} at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {} at pokecube.legends.spawns.WormholeSpawns.init(WormholeSpawns.java:142) ~[?:3.12.1] {re:classloading,pl:capability_inject_definalize:A} at pokecube.legends.init.SetupHandler.setup(SetupHandler.java:15) ~[?:3.12.1] {re:classloading} at net.minecraftforge.eventbus.ASMEventHandler_196_SetupHandler_setup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {} at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.eventbus.EventBus$$Lambda$2609/428506348.invoke(Unknown Source) ~[?:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {} at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading} at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading} at net.minecraftforge.fml.ModContainer$$Lambda$3252/47710680.run(Unknown Source) ~[?:?] {} at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {} at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {} at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {} at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {} at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames} at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

#### What I expected to happen:
Normal startup

____
#### Affected Version:

- Pokecube AIO 3.13.0.b
- Minecraft: 1.16.5
- Forge: 36.2.4

**Comment by Thutmose** [comment]
can you include the actual crash report file, rather than just that section of it?

**Comment by Thutmose** [comment]
especially since your section there does not match the versions you put in the Affected Version section

**Comment by aqswde40** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 9/5/21 6:03 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6409/2049070779.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5808/665402618.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$493/951819642.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.Thread.getStackTrace(Thread.java:1552) ~[?:1.8.0_51] {}
-- World Downloader Mod - Core --
Details:
	WDL version: 4.1.1.0
	Minecraft version: Minecraft 1.16.5 (1.16.5-forge-36.1.0/forge/release)
	Expected version: 1.16.4
	Protocol version: 754
	Data version: 2584
	File location: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at java.lang.Thread.getStackTrace(Thread.java:1552) ~[?:1.8.0_51] {}
	at net.minecraft.crash.CrashReportCategory.func_85073_a(CrashReportCategory.java:99) [?:?] {re:mixin,re:classloading}
	at net.minecraft.crash.CrashReport.func_85057_a(CrashReport.java:332) ~[?:?] {re:computing_frames,xf:OptiFine:default,re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.ForgeWDL.json:MixinCrashReport,pl:mixin:A}
	at wdl.WDL.addInfoToCrash(WDL.java:1660) ~[?:?] {re:classloading}
	at wdl.WDLEvents$HooksListener.onCrashReportPopulateEnvironment(WDLEvents.java:803) ~[?:?] {re:classloading}
	at wdl.WDLHooks.onCrashReportPopulateEnvironment(WDLHooks.java:249) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.crash.CrashReport.handler$zbf000$onCrashReportPopulateEnvironment(CrashReport.java:532) ~[?:?] {re:computing_frames,xf:OptiFine:default,re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.ForgeWDL.json:MixinCrashReport,pl:mixin:A}
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:104) [?:?] {re:computing_frames,xf:OptiFine:default,re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.ForgeWDL.json:MixinCrashReport,pl:mixin:A}
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) [?:?] {re:computing_frames,xf:OptiFine:default,re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.ForgeWDL.json:MixinCrashReport,pl:mixin:A}
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:417) [?:?] {re:computing_frames,xf:OptiFine:default,re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:mixins.ForgeWDL.json:MixinCrashReport,pl:mixin:A}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6409/2049070779.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$5808/665402618.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:seamless_loading_screen.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$493/951819642.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


-- World Downloader Mod - Extensions --
Details:
	Number loaded: 2
	Hologram: Id: Hologram
Version: 2.0
Display name: Hologram support
Main author: Pokechu22
Description: 
Provides basic support for disabling holograms.
Main class: wdl.HologramHandler
Containing file: Unknown (java.lang.NullPointerException)
Implemented interfaces (2)
0: wdl.api.IEntityManager
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: cpw.mods.modlauncher.TransformingClassLoader@2123064f (cpw.mods.modlauncher.TransformingClassLoader)
Annotations (0)

	EntityRealigner: Id: EntityRealigner
Version: 1.0
Display name: Entity realigner
Main author: Pokechu22
Description: 
Realigns entities to their serverside position to deal with entities that drift clientside (for example, boats).
Main class: wdl.EntityRealigner
Containing file: Unknown (java.lang.NullPointerException)
Implemented interfaces (2)
0: wdl.api.IEntityEditor
1: wdl.api.IWDLModDescripted
Superclass: java.lang.Object
Classloader: cpw.mods.modlauncher.TransformingClassLoader@2123064f (cpw.mods.modlauncher.TransformingClassLoader)
Annotations (1)
0: @java.lang.Deprecated() (java.lang.Deprecated)


-- World Downloader Mod - State --
Details:
	minecraft: net.minecraft.client.Minecraft@7f814c6e
	worldClient: ~~NULL~~
	networkManager: ~~NULL~~
	player: ~~NULL~~
	windowContainer: ~~NULL~~
	lastClickedBlock: ~~NULL~~
	lastEntity: ~~NULL~~
	saveHandler: ~~NULL~~
	chunkLoader: ~~NULL~~
	newTileEntities: {}
	newEntities: {}
	entityPositions: {}
	newMapDatas: {}
	downloading: false
	isMultiworld: false
	propsFound: false
	startOnChange: false
	overrideLastModifiedCheck: false
	saving: false
	worldLoadingDeferred: false
	worldName: ~~NULL~~
	baseFolderName: ~~NULL~~
	serverProps: wdl.config.Configuration@43fbd29
	worldProps: wdl.config.Configuration@43fbd29
	globalProps: wdl.config.Configuration@6884cfca
	defaultProps: wdl.config.DefaultConfiguration@1d6ddb48
	gameRules: net.minecraft.world.GameRules@687a16b7

-- World Downloader Mod - Server properties --
Details:
	-: empty

-- World Downloader Mod - World properties --
Details:
	-: empty

-- World Downloader Mod - Global properties --
Details:
	TutorialShown: true
	UpdateETag: W/"6f044519c0e2cdf2982650c6adf786b13621e12d1a5bc4bb1c65e640263b5f7a"

-- Sanity checks --
Details:
	MIXIN_INVENTORYBASIC: Skipped
	MIXIN_GUIINGAMEMENU: Passed
	MIXIN_WORLDCLIENT: Passed
	MIXIN_NHPC: Passed
	MIXIN_CRASHREPORT: Passed
	ENCODING: Passed
	TRIPWIRE: Skipped
	VERSION: ~~ERROR~~ Exception: Unexpected version mismatch - expected to be running on `1.16.4' but was running on `1.16.5'!
	TRANSLATION: Passed

-- MOD pokecube_legends --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/EntityTeleportEvent
		at pokecube.legends.spawns.WormholeSpawns.init(WormholeSpawns.java:142) ~[?:3.12.1] {re:classloading,pl:capability_inject_definalize:A}
		at pokecube.legends.init.SetupHandler.setup(SetupHandler.java:15) ~[?:3.12.1] {re:classloading}
		at net.minecraftforge.eventbus.ASMEventHandler_163_SetupHandler_setup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2606/1471902568.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3249/740982099.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: pokecube-aio-1.16.5-3.12.1 (1).jar
	Failure message: Pokécube Legends (pokecube_legends) encountered an error during the common_setup event phase
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/EntityTeleportEvent
	Mod Version: 3.12.1
	Mod Issue URL: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.living.EntityTeleportEvent
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at pokecube.legends.spawns.WormholeSpawns.init(WormholeSpawns.java:142) ~[?:3.12.1] {re:classloading,pl:capability_inject_definalize:A}
	at pokecube.legends.init.SetupHandler.setup(SetupHandler.java:15) ~[?:3.12.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_163_SetupHandler_setup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2606/1471902568.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3249/740982099.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 16485120488 bytes (15721 MB) / 20199768064 bytes (19264 MB) up to 25769803776 bytes (24576 MB)
	CPUs: 20
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |SIDED_SETU|NOSIGNATURE
		biggerchathistory_1.0.0_MC_1.16.2-1.16.5.jar      |BiggerChatHistory             |biggerchathistory             |1.0.0               |SIDED_SETU|NOSIGNATURE
		ClientTweaks_1.16.3-5.3.0.jar                     |Client Tweaks                 |clienttweaks                  |5.3.0               |SIDED_SETU|NOSIGNATURE
		fullbrightnesstoggle_1.16.5-1.2.jar               |Full Brightness Toggle        |fullbrightnesstoggle          |1.2                 |SIDED_SETU|NOSIGNATURE
		configuration-1.16.5-1.2.0.jar                    |Configuration                 |configuration                 |1.2.0               |SIDED_SETU|NOSIGNATURE
		xray-1.16.4-2.6.0.jar                             |Advanced XRay                 |xray                          |2.6.0               |SIDED_SETU|NOSIGNATURE
		AttributeFix-1.16.5-10.1.3.jar                    |AttributeFix                  |attributefix                  |10.1.3              |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		car-1.16.5-1.0.17.jar                             |Ultimate Car Mod              |car                           |1.16.5-1.0.17       |SIDED_SETU|NOSIGNATURE
		torohealth-1.16.4-forge-4.jar                     |ToroHealth                    |torohealth                    |NONE                |SIDED_SETU|NOSIGNATURE
		justplayerheads_1.16.5-1.7.jar                    |Just Player Heads             |justplayerheads               |1.7                 |SIDED_SETU|NOSIGNATURE
		Neat+1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |SIDED_SETU|NOSIGNATURE
		Xaeros_Minimap_21.14.0_Forge_1.16.5.jar           |Xaero's Minimap               |xaerominimap                  |21.14.0             |SIDED_SETU|NOSIGNATURE
		collective-1.16.5-2.60.jar                        |Collective                    |collective                    |2.60                |SIDED_SETU|NOSIGNATURE
		Clumps-6.0.0.25.jar                               |Clumps                        |clumps                        |6.0.0.25            |SIDED_SETU|NOSIGNATURE
		XaerosWorldMap_1.15.0.1_Forge_1.16.5.jar          |Xaero's World Map             |xaeroworldmap                 |1.15.0.1            |SIDED_SETU|NOSIGNATURE
		modernlife-1.16.5-1.12 (1).jar                    |Modern Life                   |modernlife                    |1.16.5-1.12         |SIDED_SETU|NOSIGNATURE
		[1.16.5]+SecurityCraft+v1.8.23.jar                |SecurityCraft                 |securitycraft                 |v1.8.23             |SIDED_SETU|NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |SIDED_SETU|NOSIGNATURE
		seamless_loading_screen-1.16.5-1.1.6.jar          |Seamless Loading Screen       |seamless_loading_screen       |1.16.5-1.1.6        |SIDED_SETU|NOSIGNATURE
		MaxHealthFix-1.16.5-1.0.2.jar                     |MaxHealthFix                  |maxhealthfix                  |1.0.2               |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Bookshelf-1.16.5-10.2.15.jar                      |Bookshelf                     |bookshelf                     |10.2.15             |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		EnchantmentDescriptions-1.16.5-7.0.12.jar         |EnchantmentDescriptions       |enchdesc                      |7.0.12              |SIDED_SETU|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		simpleplanes-1.16.5-4.6.0.jar                     |Simple Planes                 |simpleplanes                  |1.16.5-4.6.0        |SIDED_SETU|NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |SIDED_SETU|NOSIGNATURE
		FpsReducer-mc1.16.5-1.19.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.5-1.19       |SIDED_SETU|NOSIGNATURE
		exp_ore-1.16.4-1.2.jar                            |Exp Ore Block                 |exp_ore                       |1.2                 |SIDED_SETU|NOSIGNATURE
		BetterThanMending-1.6.0.jar                       |BetterThanMending             |betterthanmending             |1.6.0               |SIDED_SETU|NOSIGNATURE
		[1.16.5][Forge]+RPG-HUD-3.8.4.jar                 |RPG-Hud                       |rpg-hud                       |3.8.4               |SIDED_SETU|NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		pokecube-aio-1.16.5-3.12.1 (1).jar                |Thut Core                     |thutcore                      |99.3.12.1           |SIDED_SETU|NOSIGNATURE
		speedometer-3.0.jar                               |Speedomiter                   |speedometer                   |3.0                 |SIDED_SETU|NOSIGNATURE
		LavaClearView-1.16.2-1.1.0.jar                    |Lava Clear View               |clearview                     |1.1.0               |SIDED_SETU|NOSIGNATURE
		WorldDownloader-forge-4.1.1.0-mc1.16.4.jar        |World Downloader (Forge)      |wdl                           |4.1.1.0             |SIDED_SETU|NOSIGNATURE
	Crash Report UUID: 130c96ce-1189-4288-90d0-3d7fdaa0caf1
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 27.20.100.9127
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 20

**Comment by Thutmose** [comment]
Update forge, you are still using 36.1.0, not the 36.2.4 that you had listed
