### ISSUE TITLE
When summoning caught Pokemobs, they register as wild

### ISSUE THREAD

**Issue by Chrisjohnson57387** [Pokecube-Development/Pokecube-Issues-and-Wiki#844]
#### Issue Description:
When summoning caught Pokemobs, they register as wild. 

#### What happens:
This only seems to be an issue on my server, where the sizes of the Pokemobs are adjusted. 
When summoning caught Pokemobs, they aren't selected. You can get them to be selected if right click them, and if you hit the gui buttons "RT" then "X"(red), they should select. Sometimes also "Y".

#### What you expected to happen:
When summoning caught Pokemobs, they should be selected on releasing from the ball.

#### Steps to reproduce:
The problem isn't happening to me anymore, but the first time I ever had this issue, it occurred when I changed the size of the pokemobs from the config file, without a server restart. It solved after restarting the server.

The next time this happened, it happened after I upgraded from 3.14.0.i to 3.14.0.j. In my configs, I had also changed the sizing from 1.5 to 1.2, as well as various ai settings to lower the spawning a bit. I also had updated some of the mods I had on at the time, and added some other mods to improve performance; I'm listing them again beneath the full mod list
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube AIO: 3.14.0.j
- Minecraft: 1.18.1
- Forge: 39.0.9

**Full mod list**
- AdHooks-1.18.1-7.0.0.0-build.0041
- AdLods-1.18.1-5.0.0.0-build.0044
- advancednetherite-1.9.0-1.18
- alexsmobs-1.15.1
- AllTheCompatibility-1.18-(v.1.1.0)
- AllTheCompressed-1.0.1-1.18.1-39.0.8
- alltheores-1.7.5-1.18.1-39.0.0
- appleskin-forge-mc1.18-2.2.0
- appliedenergistics2-10.0.0-beta.3
- Aquaculture-1.18.1-2.3.2
- architectury-3.4.9
- areas_1.18.1-2.9
- ars_nouveau-1.18.1-2.0.2
- artifacts-1.18.1-4.0.2
- Assembly Line-1.18.1-0.3.2-0
- AttributeFix-Forge-1.18.1-13.0.3
- AutoRestart-1.18.1-2.0.0
- awesomedungeon-2.0.2
- Ballistix-1.18.1-0.3.5-1
- balm-2.4.0+0
- Blastcraft-1.18.1-0.2.2-0
- blockui-1.18-0.0.34-ALPHA
- carryon-1.18.1-1.17.0.5
- Chunky-1.2.164
- citadel-1.10.8-1.18
- Cleanse-1.18-7.0.0.0
- cloth-config-6.1.48-forge
- collective-1.18.1-3.8
- comforts-forge-1.18-5.0.0.1
- configured-1.5.1-1.18.1
- CosmeticArmorReworked-1.18.1-v1
- create-mc1.18.1_v0.4b
- CreativeCore_v2.4.1_mc1.18.1
- Cucumber-1.18.1-5.0.2
- curios-forge-1.18.1-5.0.4.2
- CustomStartingGear-1.18.1-2.0.3.1-universal
- dimdungeons-1.13.1-forge-1.18.1
- DoggyTalents-1.18.1-2.4.0
- domum_ornamentum-1.18-1.0.31-ALPHA-universal
- dpanvil-1.18.1-3.2.0
- DungeonCrawl-1.18.1-2.3.6
- dynview-1.18-2.3
- EasyMagic-v3.2.1-1.18.1-Forge
- Electrodynamics-1.18.1-0.5.4-0
- elementalcraft-1.18.1-4.1.6
- enhancedcelestials-2.0.9-1.18
- EnhancedVisuals_v1.4.3_mc1.18.1
- excavation-1.18-1.7
- expandability-5.0.0-forge
- expandedstorage-7.3.6+1.18
- ExplorersCompass-1.18.1-1.1.2-forge
- flywheel-forge-1.18-0.5.0a
- ForgeEndertech-1.18.1-8.0.0.0-build.0040
- geckolib-1.18-forge-3.0.3
- Gobber2-Forge-1.18.1-2.6.10
- goblintraders-1.7.0-1.18.1
- guardvillagers-1.18.1.4.0
- Guide-API-VP-1.18.1-2.2.3-beta.1
- HarderFarther-1.18.1-18.39.0.6
- ImmersiveEngineering-1.18.1-7.1.0-145
- ironfurnaces-1.18.1-3.1.3
- Jade-1.18-4.1.0
- kubejs-create-1801.2.0-build.14
- kubejs-forge-1801.4.0-build.263
- kubejs-immersive-engineering-1801.2.0-build.16
- LibraryFerret-Forge-1.18.1-1.0.2
- LibX-1.18.1-3.1.0
- limitedchunks-1.18-2.1
- mahoutsukai-1.18.1-v1.33.7
- malum-1.18.1-1.1.3
- MCDoom-1.18.1-4.0.1
- mcw-bridges-2.0.1-mc1.18.1
- mcw-doors-1.0.5-mc1.18.1
- mcw-fences-1.0.2-mc1.18.1
- mcw-lights-1.0.2-mc1.18.1
- mcw-paintings-1.0.2-mc1.18.1
- mcw-trapdoors-1.0.4-mc1.18.1
- mcw-windows-2.0.2-mc1.18.1
- minecolonies-1.18.1-1.0.278-RELEASE
- MobileBeacons1.18.1(FORGE)v1.0.0
- MoreVanillaLib-1.18.1-3.0.3
- MouseTweaks-forge-mc1.18-2.21
- multi-piston-1.18-1.2.2-ALPHA
- MysticalAgriculture-1.18.1-5.0.1
- MysticalCustomization-1.18.1-3.0.0
- NaturesCompass-1.18.1-1.9.4-forge
- ninjaphenix-container-library-1.2.10+1.18
- Nuclear Science-1.18.1-0.4.2-0
- occultism-1.18.1-1.24.0
- out_of_sight-1.18.1-1.0.1
- Patchouli-1.18.1-63
- pokecube-aio-1.18.1-3.14.0.j
- polymorph-forge-1.18.1-0.35
- PuzzlesLib-v3.1.3-1.18.1-Forge
- randomvillagenames_1.18.1-1.5
- repurposed_structures_forge-4.1.0+1.18.1
- respawningshulkers_1.18.1-1.7
- rhino-forge-1800.1.7-build.92
- RootsClassic-1.18-1.1.16
- RoughlyEnoughItems-7.1.357
- RoughlyEnoughItems-jei-internals-workaround-7.1.357
- RuneCraft-1.18-(v.3.3.1)
- scannable-1.18.1-forge-1.7.6+da03abb
- setworldspawnpoint_1.18.1-1.9
- sophisticatedbackpacks-1.18.1-3.15.0.494
- SpawnBalanceUtility-1.18.1-1.39.0.11
- spellsword-1-18-1
- structurize-1.18.1-1.0.319-BETA
- swingthroughgrass-1.18.1-1.8.0
- Terralith_v2.0.9_Fabric+Forge
- The_Graveyard_1.1_(FORGE)_for_1.18.1
- tombstone-7.3.2-1.18
- valhelsia_core-1.18.1-0.3.0
- valhelsia_structures-1.18.1-0.1.0
- VampiresNeedUmbrellas-1.18.1-1.0
- Vampirism-1.18.1-1.8.0-alpha+20210102-1316
- VanillaExcavators-1.18.1-4.0.0
- VanillaHammers-1.18.1-4.0.0
- villagebellrecipe_1.18.1-1.4
- villagernames_1.18.1-3.5
- villagertools-1.18-1.0.2
- VTweaks-1.18-3.5.4
- waystones-forge-1.18.1-9.0.1
- weirdmobs-1-18-1
- Xaeros_Minimap_21.23.0_Forge_1.18
- XaerosWorldMap_1.19.0_Forge_1.18

**Updated mods at the same time I updated pokecube**
- appliedenergistics2-10.0.0-beta.3
- ars_nouveau-1.18.1-2.0.2
- awesomedungeon-2.0.2
- Cucumber-1.18.1-5.0.2
- EasyMagic-v3.2.1-1.18.1-Forge
- elementalcraft-1.18.1-4.1.6
- kubejs-immersive-engineering-1801.2.0-build.16
- ninjaphenix-container-library-1.2.10+1.18
- occultism-1.18.1-1.24.0
- polymorph-forge-1.18.1-0.35
- repurposed_structures_forge-4.1.0+1.18.1
- RuneCraft-1.18-(v.3.3.1)
- Terralith_v2.0.9_Fabric+Forge
- valhelsia_core-1.18.1-0.3.0
- Vampirism-1.18.1-1.8.0-alpha+20210102-1316

**Mods I added at the same time I updated pokecube**
- limitedchunks-1.18-2.1
- SpawnBalanceUtility-1.18.1-1.39.0.11
- swingthroughgrass-1.18.1-1.8.0

**Comment by Thutmose** [comment]
I am currently marking this as "cannot replicate", as you mentioned that it seems to randomly fix itself, hopefully if it happens to someone else, or later, then there will be more information about the specific details?

**Comment by Chrisjohnson57387** [comment]
The only notable thing that happened before it working and after was that my power went out.

**Comment by Chrisjohnson57387** [comment]
Pokemobs will automatically reselect if they level up while fighting

**Comment by Chrisjohnson57387** [comment]
This issue happens always after a crash now. It's been hard to diagnose what mod may be conflicting with Pokecube because I can disable random mods and then the game will work, only to reenable those same mods and it still work. I've then tried to do so with a different set of mods, and the behavior holds up. It's not clearly any mod as far as I can see, or it's multiple mods and I don't know what they have in common. When this issue is happening, the below is in the client log for every pokemon in renderable distance:
`[07:50:39] [Render thread/FATAL]: Error executing task on Client
java.lang.IllegalStateException: Invalid entity data item type for field 30 on entity GenericPokemob['Ponyta'/1725, l='ClientLevel', x=-812.82, y=71.00, z=-523.40]: old=0(class java.lang.Byte), new=(0.0, 0.0, 0.0) 00000000-0000-0000-0000-000000000000(class thut.api.entity.IMultiplePassengerEntity$Seat)
	at net.minecraft.network.syncher.SynchedEntityData.m_135375_(SynchedEntityData.java:245) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.network.syncher.SynchedEntityData.m_135356_(SynchedEntityData.java:232) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_6455_(ClientPacketListener.java:434) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5797_(ClientboundSetEntityDataPacket.java:39) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.network.protocol.game.ClientboundSetEntityDataPacket.m_5797_(ClientboundSetEntityDataPacket.java:11) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1009) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23197!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.9.jar%2323!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]`
